### PR TITLE
Blog post about Aus community call

### PR DESCRIPTION
**Pull request by DamienIrving**
cc @sheraaronhurt, @maneesha

(Sorry about the delay on getting this post up - I actually submitted a PR a couple of weeks ago but accidentally did it against the `gh-pages` branch of my fork instead of the carpentries.org. repo)

### CODE REVIEW

**Comment by maneesha** [comment]
Thanks @DamienIrving 
I think @sheraaronhurt  should review this; then we can merge.

**Comment by kariljordan** [comment]
Thank you @DamienIrving! 

@serahrono will merge this post after @sheraaronhurt reviews. Serah has a blog schedule and we want to make sure the post gets maximum visibility! We try not to post multiple posts on any given day. Thanks again!

**Review by sheraaronhurt — APPROVED** [review]
Great post @DamienIrving  Thanks!

**Review by serahkiburu — APPROVED** [review]
Thanks for writing Damien! Great summary! I went in and changed the publishing date and tweaked the title a bit.

**Pull request merged**
