### PR TITLE
add new Director of Partnerships to team page

### PR DESCRIPTION
**Pull request by maneesha**

### CODE REVIEW

**Comment by maneesha** [comment]
I had to crop Al's image so I emailed a preview of it to him and @ErinBecker .
Once Al approves the image, this can be merged along with #1019 by @kmomar

**Comment by kariljordan** [comment]
Hi @maneesha! Thanks so much for updating this page! Can you make two small changes? Core Team members should be listed in alphabetical order by last name after Executive Team. Also, is there a way to crop @Al-Obayuwana's photo so that he's in the center? There's a lot of brick on the right side (LOL!)

**Comment by maneesha** [comment]
Thanks @kariljordan 
I was going by what I thought @ErinBecker  wanted, with team members listed in reverse alpha order by first name (which is why Zhian comes first and Al comes last).  
The picture Al shared was off center, so I was trying to preserve that.  I change that if you and he would like.

**Comment by ErinBecker** [comment]
Thanks @maneesha. You are right about the order. We are doing reverse alpha by first name after ET. (Two years ago we were alpha by last name 😄 ). Please do adjust the photo so Al is in the center and go ahead and merge. Thank you!

**Comment by Al-Obayuwana** [comment]
Thanks all, you know I'm a little off balance :)

**Comment by maneesha** [comment]
Al's original headshot was asymmetrical.  I've adjusted it so that he's more on center.  Now that I have his GitHub id, I've also added that in as well.

**Pull request merged**
