### PR TITLE
Glosario Hacktoberfest Follow-Up Post

### PR DESCRIPTION
**Pull request by tobyhodges**
@kmomar I guessed at a suitable publication date, please let me know what I should change it to.

and pinging @gvwilson to see if he'd like to add anything...

### CODE REVIEW

**Comment by kmomar** [comment]
Hi @tobyhodges! There is currently a blog post slated to be published on 11/25 announcing our new regional coordinator. If you are amenable to it, would be be able to publish this on the 2nd of December? Conversely, I can go back to Sher! and ask to move that blog post to the week after. Let me know!

**Comment by tobyhodges** [comment]
No worries @kmomar I've updated the publication date now. Let's leave this open for a few days, in case Greg would like to add anything.

**Comment by gvwilson** [comment]
LGTM

**Comment by tobyhodges** [comment]
ok then it looks like this one is ready to be queued up

**Pull request merged**
