### PR TITLE
CAC links

### PR DESCRIPTION
**Pull request by maneesha**

### CODE REVIEW

**Comment by maneesha** [comment]
This updates the information here (https://carpentries.org/community/#curriculum-advisors) fixing a broken link to the handbook and linking to the new https://carpentries.org/curriculum-advisors/ page.

@ErinBecker  is it correct that *We are not currently seeking new members to the Curriculum Advisory Committees*?

**Comment by maneesha** [comment]
Bump @ErinBecker

**Comment by maneesha** [comment]
Reminder @ErinBecker

**Comment by ErinBecker** [comment]
Thank you Maneesha. These can be merged.

**Comment by maneesha** [comment]
Thanks @ErinBecker 
I also wanted to check about my question above:

>  is it correct that We are not currently seeking new members to the Curriculum Advisory Committees?

**Comment by ErinBecker** [comment]
That is correct. Toby will start recruiting new members for some of the CACs in the next few months, but currently we are not accepting applications for any CAC.

**Pull request merged**
