### PR TITLE
Enable matomo, remove Google Analytics

### PR DESCRIPTION
**Pull request by fmichonneau**
This PR should be ready to go but internal communication needs to happen first.

### CODE REVIEW

**Comment by kariljordan** [comment]
@fmichonneau is this an update that we'll need to share with the entire core team, or only community development (because of communications) and infrastructure?

**Comment by maneesha** [comment]
@fmichonneau  Should we keep this PR open as is, or consider something new as we put out our privacy policy and other systems?

**Comment by maneesha** [comment]
Checking in @fmichonneau

**Comment by maneesha** [comment]
Pinging @fmichonneau

**Comment by ashwinvis** [comment]
Matomo would be great to have in the lesson templates in place of Google Analytics. See https://github.com/carpentries/styles/issues/290. Wouldn't it be better for the learner's experience to avoid personal information and cookie banners altogether? It is possible if Matomo is configured in such a way.

https://matomo.org/cookie-consent-banners/

**Pull request merged**
