### PR TITLE
Member listing

### PR DESCRIPTION
**Pull request by maneesha**
Updates the [member page](https://carpentries.org/members/) so it is automatically built from our [feeds](https://feeds.carpentries.org/).

### CODE REVIEW

**Comment by elletjies** [comment]
@maneesha this looks great! I am not sure if it is only me but the flags don't look the same size. some of them look stretched a bit too (for example the Australia flag)

**Review by elletjies — APPROVED** [review]
Some of the flags look a bit stretched. Anything we can do about this?

**Comment by maneesha** [comment]
@elletjies This is because [national flags are not all the same size](https://en.wikipedia.org/wiki/List_of_aspect_ratios_of_national_flags).   It becomes more apparent when you see them all close to each other, and is not as apparent when they are spaced out on [a page like this](https://carpentries.org/instructors/), but the difference is still there.

**Comment by fmichonneau** [comment]
I think it'd be nice to add the GPS coordinates for the institutions in the feed so we can build a map to show our reach.

**Comment by elletjies** [comment]
Is there also a way to click on for example the ZA flag and get a list of all the ZA members?

**Comment by maneesha** [comment]
Thanks @fmichonneau  and @elletjies 
I think those are both great ideas.  I think clicking on a flag to see other orgs in that country may be more challenging to build. Having a map would be easier and help meet this end though.   

I'd like to get this PR merged first and then address those separately, so I will open another issue for those.  @Al-Obayuwana  I'd like to get your approval as membership lead - let me know if this looks good to you for now.  You can use the "Browse the preview" link above.  Thanks!

**Comment by maneesha** [comment]
Reviewed this with @Al-Obayuwana  during a 1:1 meeting, merging as he says it looks good.

**Pull request merged**
