### PR TITLE
add in lesson program blog posts

### PR DESCRIPTION
**Pull request by maneesha**
Moves DC blog posts from the DC website to this website including adding a "Data Carpentry" tag to each of those posts and adding a note at the top of the post saying it was originally published on the DC website.

### CODE REVIEW

**Comment by maneesha** [comment]
This should be merged at the same time as https://github.com/datacarpentry/datacarpentry.github.io/pull/606 and https://github.com/swcarpentry/website/pull/1261 and the forthcoming LC PR.

**Comment by maneesha** [comment]
To do: Add layout to each imported blog post

**Comment by elletjies** [comment]
@maneesha can I approve this PR?

**Comment by maneesha** [comment]
@elletjies This is something I have shared with Oscar. If you would also like to review and add your feedback/approval, please do. I will be waiting to discuss with Oscar when we should merge everything.

**Pull request merged**
