### PR TITLE
proposing standalone page for quarterly Core Team projects

### PR DESCRIPTION
**Pull request by serahkiburu**
@kariljordan and @ErinBecker, this PR has a suggested first format for our standalone projects page. Here's what it looks like - quarterly sections under each team are collapsible (expand and collapse on click)

Quarterly Team Projects in The Carpentries

### CODE REVIEW

**Comment by serahkiburu** [comment]
Projects are listed in alphabetical order, as are team member names under each team name. Does this work well?

**Comment by kariljordan** [comment]
I really like listing the projects in alpha order. For team member names, can we put the team lead's name in bold, or any other way to show who is the leader of that team? Also, I'm fine with having the Executive Team projects listed on this page as opposed to a separate page. This is fine work @serahrono!

**Review by kariljordan — CHANGES_REQUESTED** [review]
I really like listing the projects and team members in alpha order. Also, I'm fine with having the Executive Team projects listed on this page as opposed to a separate page. This is fine work @serahrono!

Suggestions/requests:

- Add Executive Team projects to this page
- Remove Kari from Workshop Admin Team
- Change Business Team lead to Elizabeth in the paragraph about the Business Team

Question: Do we want to include team members who no longer work for The Carpentries?

**Comment by serahkiburu** [comment]
Hi @kariljordan, changes implemented:

I removed your name and added provision to write in quarterly updates about Leadership Team's work. Please share the work summaries for Q2, Q3 and Q4 and I will slot them in.

Instead of bolding the names of Team Leads (we would need to explain what that meant) each Team section starts with the sentence ' Led by [person's name], [team name]...'

**Comment by ErinBecker** [comment]
@serahrono - this is amazing! Thank you so much for putting this together. Just a couple of comments and suggestions:

1. There are some links that aren't showing up as rendered in the PR preview. This appears to be limited to links in the **January - March (Q1) 2019** sections. My guess is this is something odd with the preview rather than an issue with the links themselves, but wanted to draw your attention to it.

Example: 
Screen Shot 2020-02-07 at 9 21 46 AM

2. Since this page will continue to grow each quarter, I suggest further collapsing the project lists under each team. For example, we could have the team description followed by an "Our Projects" drop-down arrow, which then shows what now shows up on the page (each quarter's projects) **OR** "Our Projects" could then lead to a further drop-down that displays years, which then displays quarters. There's a trade off between immediacy (how many arrows the user needs to click before getting to the projects) and cleanness of the page. I'm not sure what the best solution is, but thought I'd suggest these options as possibilities.

3. For quarters where a specific team doesn't have a project (e.g. Business Team Q1 2020), it would be nice to have some default text that says something like "This team did not have any projects this quarter, and is focusing on ongoing work."

These are all really minor issues. Overall, this page looks great and I'm really excited to see it go live! Thanks @serahrono!

**Review by ErinBecker — COMMENTED** [review]
Please see my comments in the thread. Thanks @serahrono!

**Comment by serahrono** [comment]
thanks @ErinBecker!

1. You are right that that's a rendering issue with the preview rather than a syntax issue, the link looks good on the final page 

2. Nesting is something worth thinking a bit more about -particularly how to execute. In deciding how to present information, I played around with the idea of using navigation tabs and collapsible sections together- this seemed like the ideal to present all the information we want to put out on the page. However, navtabs require a bit more time to execute right now, so I have marked it as a "nice to have" task for when there's a little more time. 

If you're ok with us publishing this as is now, then discussing our options for nesting content at our in-person next week, I would prefer to workshop it with as many of us on the team as possible. Please let me know if this works.

3. I love that suggestion, and will definitely take it up for all quarters going forward. My workflow for this is currently:
[ ] review project planning doc for each team 
[ ] create project summary paragraph from context narrative and aims of the project as laid out by the team
[ ] translate that to Markdown and submit PR
[ ] invite team to review (final preview on GitHub) and offer more details. This is where teams without a specific project would confirm they are focussing on ongoing work
[ ] update core-team-projects page
[ ] at the end of the quarter, link to all outputs from specific projects (videos, blog posts, repositories, documentation, issues, etc)

what do you think, @ErinBecker @kariljordan ?

**Comment by serahkiburu** [comment]
thanks @ErinBecker!

1. You are right that that's a rendering issue with the preview rather than a syntax issue, the link looks good on the final page 

2. Nesting is something worth thinking a bit more about -particularly how to execute. In deciding how to present information, I played around with the idea of using navigation tabs and collapsible sections together- this seemed like the ideal to present all the information we want to put out on the page. However, navtabs require a bit more time to execute right now, so I have marked it as a "nice to have" task for when there's a little more time. 

If you're ok with us publishing this as is now, then discussing our options for nesting content at our in-person next week, I would prefer to workshop it with as many of us on the team as possible. Please let me know if this works.

3. I love that suggestion, and will definitely take it up for all quarters going forward. My workflow for this is currently:
- [ ] review project planning doc for each team 
- [ ] create project summary paragraph from context narrative and aims of the project as laid out by the team
- [ ] translate that to Markdown and submit PR
- [ ] invite team to review (final preview on GitHub) and offer more details. This is where teams without a specific project would confirm they are focussing on ongoing work
- [ ] update core-team-projects page (by merging PR)
- [ ] at the end of the quarter, link to all outputs from specific projects (videos, blog posts, repositories, documentation, issues, etc)

what do you think, @ErinBecker @kariljordan ?

**Comment by kariljordan** [comment]
Hi @serahrono, thank you for providing the proposed workflow. This sounds good. I am concerned that it will take a lot of time for you to summarize each project though, so maybe we can discuss more about that in our meeting. I'm wondering how project leads can take a little more ownership in this process.

**Comment by serahkiburu** [comment]
hi @ErinBecker @kariljordan 👋 this is how the updated page looks, with the Executive Team's Projects section expanded to show how that will look for each of the team
Quarterly Team Projects in The Carpentries (2)

**Comment by serahkiburu** [comment]
this is now ready to merge

**Comment by kariljordan** [comment]
LGTM!! Awesome work!

**Comment by ErinBecker** [comment]
LGTM!

**Review by ErinBecker — APPROVED** [review]
Looks good to me! Ready to merge.

**Review by kariljordan — APPROVED** [review]

**Comment by serahkiburu** [comment]
thanks @ErinBecker and @kariljordan

**Pull request merged**
