### PR TITLE
update length guidance for alt-text in images in accathon blog post

### PR DESCRIPTION
**Pull request by zkamvar**
There is no character limit:https://yatil.net/blog/there-is-no-character-limit-for-alt-text

### CODE REVIEW

**Comment by maneesha** [comment]
Thanks @zkamvar 
Tagging @brynnelliott for review before merging.

**Comment by maneesha** [comment]
Bump @brynn

**Comment by brynnelliott** [comment]
There is no limit on characters - depending on what you read. My suggestion as a best practice is to keep it short 100-125 characters. However, if it is something that needs a long explanation such as a chart or a graph, use a two-part alt. text. The first is a short description to identify the image and the second is a long a textual representation of the essential information conveyed by the image. 

Does this help?

**Comment by maneesha** [comment]
Thanks @brynnelliott  Are you ok with Zhian's recommendation or should we expand it to note what you've said in your comment?

**Comment by brynnelliott** [comment]
@maneesha  my recommendation is "Keep it short (100-125 characters is optimal)"

**Comment by maneesha** [comment]
Updated based on recommendation from @brynnelliott

**Pull request merged**
