### PR TITLE
Add R Tips and Tricks blog post by Bianca and Katrin

### PR DESCRIPTION
**Pull request by serahkiburu**

### CODE REVIEW

**Comment by ErinBecker** [comment]
@serahrono - can we hold off on posting this until tomorrow afternoon? I have a coordinated post going out here and on the DC blog that was scheduled for today.

**Comment by serahkiburu** [comment]
sure thing @ErinBecker

**Comment by kariljordan** [comment]
I'm also planning to post the equity and inclusion roadmap on Thursday. Are all of these posts on the communications calendar in Asana? Wondering how we can coordinate better...

**Comment by serahkiburu** [comment]
Go ahead and post @kariljordan, i'll keep this for Friday morning. 

We publish community-scribed posts as they become available /get submitted for review, so sometimes there's overlap with posts scheduled ahead of time on the community calendar.

**Pull request merged**
