### PR TITLE
Added translation of "Data Carpentry Python Ecology Lesson Translated into Spanish"

### PR DESCRIPTION
**Pull request by NPalopoli**
Created file "2019-01-22-python-ecologia-es.md" as a translation of "Data Carpentry Python Ecology Lesson Translated into Spanish" originally posted in English [2019-01-17-python-ecology-es.md](https://github.com/carpentries/carpentries.org/blob/gh-pages/_posts/2019/01/2019-01-17-python-ecology-es.md).

### CODE REVIEW

**Comment by fmichonneau** [comment]
Thanks for your work on this @NPalopoli :fireworks: Is this ready to merge? May I have a +1 from @raynamharris @orchid00 or @Helysalgado?

**Comment by raynamharris** [comment]
+1 from me! Thanks @NPalopoli and @fmichonneau

**Comment by Helysalgado** [comment]
+1 from me, but including the original name as a reference.

**Comment by raynamharris** [comment]
Ah, yes, maybe add "[_Read the English version of this blog post here._](https://carpentries.org/blog/2019/01/python-ecology-es/)" to the top of this post and I'll add "[_Lee la versión en español de este blog aquí._](https://carpentries.org/blog/2019/01/python-ecologia-es/)" to the top of the original so that they both link to each other

**Comment by NPalopoli** [comment]
Thanks for the feedback. I've commited a reference to the original post in English, so this should be ready to merge now :smile:

**Comment by fmichonneau** [comment]
thank you all!

**Pull request merged**
