### PR TITLE
Posted CoC Documentation RFC

### PR DESCRIPTION
**Pull request by kariljordan**
I would like this blog post to be posted at [12:00 UTC](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2019&month=1&day=31&hour=12&min=0&sec=0&p1=5576)/ 7am eastern. @tracykteal needs to read through it once more before it's merged. Assigning to either @maneesha or @ErinBecker to merge. Thanks all!

### CODE REVIEW

**Comment by maneesha** [comment]
@kariljordan  My understanding is that blog posts can't be scheduled; they go live as soon as they are pushed.  If @tracykteal  or @ErinBecker  approves this post here, I can set a reminder to get online tomorrow morning at 7 am Eastern to push this live.

**Comment by jduckles** [comment]
It can be configured to work, but since we only have the site re-buiit when a GitHub action occurs (PR merge, Push, etc) it won't work quite as expected (there could be up to a 23-hour delay from the set time in the blog post, we have a daily site re-build configured). To make future dated posts not appear you can set `future: false` in `_config.yml` so future dated posts don't get built. Then we'd need a cron job to trigger a site build every hour or so.

**Comment by ErinBecker** [comment]
Looks like @tracykteal needs to approve the final language (not me, as I haven't been involved with the CoC committee the past year). Once @tracykteal approves the post, @maneesha can post at 7am Eastern. We'll need to get one of the strategies @jduckles mentioned working in the long-term to avoid the need to push merge at a specific time, though. @fmichonneau and @maneesha can you add this to the (incredibly long) wish list for infrastructure?

**Comment by kariljordan** [comment]
I just spoke with @tracykteal and she has approved this post.

**Comment by tracykteal** [comment]
Thanks, yes LGTM!

**Pull request merged**
