### PR TITLE
Fix1795 governance chairs

### PR DESCRIPTION
**Pull request by maneesha**

### CODE REVIEW

**Comment by maneesha** [comment]
Fixes #1795

**Comment by maneesha** [comment]
@kariljordan  You can [preview the governance page here](https://deploy-preview-1799--stupefied-einstein-5bde90.netlify.app/governance/).

**Comment by maneesha** [comment]
Reminder @kariljordan

**Comment by kariljordan** [comment]
My apologies, my GitHub notifications were hidden in my email.

**Review by kariljordan — APPROVED** [review]
Thanks so much!

**Pull request merged**
