### PR TITLE
change team name WAT to WIT

### PR DESCRIPTION
**Pull request by maneesha**

### CODE REVIEW

**Comment by maneesha** [comment]
Changes "Workshop Administration Team" to "Workshops and Instruction Team"

**Comment by maneesha** [comment]
@sheraaronhurt  if this looks good to you, you can merge.  I have put in changes to these two pages.  We don't refer to the team on any other pages.

* [Workshops page](https://deploy-preview-1804--stupefied-einstein-5bde90.netlify.app/workshops/)
* [Workshops FAQ page](https://deploy-preview-1804--stupefied-einstein-5bde90.netlify.app/workshop_faq/)

**Comment by sheraaronhurt** [comment]
@maneesha LGTM... does the one merge change both pages you listed above?

**Comment by maneesha** [comment]
@sheraaronhurt Yes - this will do it.  Thanks!

**Pull request merged**
