### PR TITLE
draft blog post

### PR DESCRIPTION
**Pull request by maglet**
wait to post till we get @mchiapello 's feedback

### CODE REVIEW

**Comment by mchiapello** [comment]
@maglet this is perfect. 
I was thinking to add a sentence about the presentation topics, something like:
> The three mentoring groups will present about lesson maintenance, teaching and organize a workshop.

Feel free to rephrase it if needed.

**Comment by maglet** [comment]
That's a great addition! I wanted to include more detail but couldn't remember the topics. I'll add that sentence and then we'll be ready to go!

**Comment by maglet** [comment]
@kariljordan this is ready to go whenever

**Comment by kariljordan** [comment]
Thank you @maglet and @mchiapello for drafting this post! I made a few minor edits, and will merge it now.

**Pull request merged**
