### PR TITLE
fix assessment links

### PR DESCRIPTION
**Pull request by fmichonneau**

### CODE REVIEW

**Comment by weaverbel** [comment]
I fixed these myself before seeing this PR @fmichonneau - maybe see if all is well ?

**Comment by fmichonneau** [comment]
My PR also included the files that aren't part of the repository currently. They need to be brought in.

**Comment by weaverbel** [comment]
Do you mean the two PDFs? I just linked to where they were sitting on the DC site. @fmichonneau I thought that was better but happy to be wrong.

**Comment by jduckles** [comment]
All three of us I think contributed contradictory fixes. Should be working now.

**Pull request closed without merging**
