### PR TITLE
add link to PDF file, make checklists accessible

### PR DESCRIPTION
**Pull request by fmichonneau**
I suggest:
- we add a date of last revision at the top of the page
- we add a link to a PDF version of the page based on @serahrono recommendation

I also updated the checklist format at little to make it accessible. Not representing the items as elements of a checklist but as form input would be disorenting for screen readers as far as I understand.

(I also deleted a file that shouldn't have been here in the first place).

Note that the link to the PDF may not work in the preview but it should work once merged.

### CODE REVIEW

**Review by serahkiburu — CHANGES_REQUESTED** [review]
Thanks for this @fmichonneau. As you can see [here](https://deploy-preview-774--stupefied-einstein-5bde90.netlify.app/online-workshop-recommendations/), we have lost the checklist effect with this change

**before**
checklists rendering well on page

**after**
checklists not propagating well on page


We can definitely improve accessibility by including labels to each html checklist item [in this section](https://github.com/carpentries/carpentries.org/pull/774/files#diff-39850f0d31d71b3772ab221d7fc1815eL51-L70) like so:

```
<input type="checkbox" id="1.1" name="1.1" value="Monitoring communications">
<label for="1.1"> Monitoring communications</label><br>
```

In case you agree, I will go ahead and add this labels for each of the items in the checklists.

Let me know what you think.

It also looks like you forgot to add the PDF under the files section, please add it.

**Comment by fmichonneau** [comment]
hmmm, this is how it looks for me:

Screenshot from 2020-05-20 18-57-42

I think it might be that I have the font locally and that it's a special character. I'll look more into it tomorrow.

The PDF file is generated by Travis at build time (and is already part of the repository) so it's not part of this PR.

If we keep the input fields, then the checklist in the PDF isn't going to be rendered properly: https://carpentries.org/files/pdf/online-workshop-recommendations.pdf

**Comment by serahkiburu** [comment]
fair enough, @fmichonneau. I think the only thing missing is some sort of Carpentries branding in the PDF. Is it possible to append ' recommendations by carpentries.org' or similar to the footer of every page in the PDF?

**Comment by fmichonneau** [comment]
Here is what it looks like now (it uses FontAwesome so it should look the same for everyone):

Screenshot from 2020-05-21 15-51-09

Thanks for the suggestion about branding the PDF file!

Here is what the header is going to look like (it inlcudes "The Carpentries, https://carpentries.org):
Screenshot from 2020-05-21 15-52-12

and the footer (it includes CC-BY 2020):
Screenshot from 2020-05-21 15-52-18

One issue I haven't found a solution for yet is that the PDF has this at the beginning of the file:

Screenshot from 2020-05-21 15-53-57


Let me know what you think!

**Comment by serahkiburu** [comment]
Thanks @fmichonneau! I quite like the way we invite people to edit our blog pages on GitHub, the link is subtly presented but unmissable. 

Screenshot 2020-05-22 at 07 29 02

Wondering if we can borrow that approach for the `this page is also available as a PDF` alert on the online recommendations page, and have that at the top where the current alert is. Does that help us get rid of this text at the top of the PDF?

image

**Comment by fmichonneau** [comment]
thanks for the suggestion Serah! Check out the preview (https://deploy-preview-774--stupefied-einstein-5bde90.netlify.app/online-workshop-recommendations/) and let me know what you think!

**Review by serahkiburu — APPROVED** [review]

**Comment by serahkiburu** [comment]
Thanks for the changes @fmichonneau, I moved the PDF link to the top of the page so it is unmissable. 

This looks great to me, please merge.

**Comment by fmichonneau** [comment]
:tada:

**Pull request merged**
