### PR TITLE
Promote GH-org-wide OpenSearch plugin 

### PR DESCRIPTION
**Pull request by katrinleinweber**
This was discussed a bit in https://carpentries.topicbox.com/groups/discuss/Ta3b20a51cb1ba874/search-across-all-carpentries-github-organizations, but mentioning the plugin here is an alternative, simpler approach.

I'm hoping this will prove useful to others in finding existing lesson material, or discussions across all Carpentries GH orgs.

In case the plugin's name should be different, please feel free to post other suggestions below and vote on them.

### CODE REVIEW

**Comment by katrinleinweber** [comment]
Neat, the browser's install suggestion works:

grafik

**Comment by katrinleinweber** [comment]
Other name suggestion: `Software, Data & Library Carpentries GitHub Orgs` (_Organizations_ would be too long).

**Comment by fmichonneau** [comment]
hey Katrin, sorry the late follow up on this. With the newer version of Firefox, it doesn't show up as a suggested search engine option for me, but installing the plugin works well!

**Comment by katrinleinweber** [comment]
Thanks for testing! I have 4 ideas what the problem could be:

- [x] omit `/` at tag closing
- [-] `hreflang` now unsupported? => remove
- [-] Fx no longer accepts external `href`? => copy XML code into this PR
- [-] included in wrong place? => move to another [_includes/*.html](https://github.com/carpentries/carpentries.org/blob/gh-pages/_includes/_head.html)?

**Comment by katrinleinweber** [comment]
It think the install suggestion depends on having the separate search bar activated:

Screen Shot 2020-05-12 at 14 06 35

**Comment by katrinleinweber** [comment]
Nonetheless, I'm open to

1. "copy[ing] XML code into this PR" and/or
1. "move[ing] to another [_includes/*.html](https://github.com/carpentries/carpentries.org/blob/gh-pages/_includes/_head.html)"

**Comment by maneesha** [comment]
Catching up on some old issues.... @katrinleinweber  @fmichonneau  is this still something we want to consider?

**Comment by katrinleinweber** [comment]
@maneesha I'm still using it :-) Rebasing & cleaning this up...

**Comment by maneesha** [comment]
Cleaning up old issues/PRs.  @fmichonneau Should we still be considering this?

**Comment by maneesha** [comment]
@fmichonneau  Let me know if we should go ahead with this

@katrinleinweber  - This is an old issue - can you let us know if the plugin still works as is?

**Comment by katrinleinweber** [comment]
@maneesha: Yes, it still works. It's installable via https://mycroftproject.com/install.html?id=102146, and if more GitHub organization have been added since I created it, MyCroft has a public "Edit/Update Plugin" option.

**Comment by fmichonneau** [comment]
Thanks Katrin!

**Pull request merged**
