### PR TITLE
Blog post about IDC meeting for August

### PR DESCRIPTION
**Pull request by maglet**

### CODE REVIEW

**Comment by maglet** [comment]
@sstevens2

**Comment by kariljordan** [comment]
@maglet I tried submitting a PR with my changes but I got a 404 error.

This blog post is so awesome. The findings are so important. For this question for the community: 

> How can we improve the discussion session form?

What form are you referring to? Can you link to it in the blog post?

**Comment by maglet** [comment]
Thanks for taking a look, Kari!

I think we were talking about slight modifications to the host and attendee forms we fill out after the discussions to make things easier to analyze, and also clarify to attendees what types of discussions they attended (most didn't know if they were in a pre-post discussion) 

@sstevens2 did you have anything to add?

**Comment by kariljordan** [comment]
Ah, that makes perfect sense. Would you or @sstevens2 mind revising that part of the post so that it's clear? I think that's an amazing idea.

**Comment by maglet** [comment]
I revised it!

**Comment by kariljordan** [comment]
Awesome. Thank you again!

**Pull request merged**
