### PR TITLE
[fix #50] add logos to front page

### LINKED ISSUE #50: Add SWC & DC Logos to the website

### PR DESCRIPTION
**Pull request by fmichonneau**
Proposed layout of logos on front page. Feedback welcome.

screenshot from 2019-03-04 10-22-02

### CODE REVIEW

**Comment by maneesha** [comment]
Thanks @fmichonneau  
I think this is good to get us started.  I was envisioning something that doesn't take up extra real estate -- something that would still let you see the three sections (what we do, who we are, get involved) above the fold.  It would take me quite some time to figure out a way to do this and make it look nice though :-).
Maybe have them moved up, so that they are in the gray photo field rather than in a new section?

In any case, I'd want to have the three Carpentry lesson programs logos be hyperlinked as well.  I'll add to this PR to add in those links to this in a bit.

**Comment by fmichonneau** [comment]
We can't put them in the gray image above because it resizes depending on the size of the screen and having them in the right location across all screen sizes would be challenging/not look good. 

We can make the logos smaller (height: 80px; padding: 30px)

screenshot from 2019-03-05 09-14-02

even smaller (height: 60px; padding: 20px)

screenshot from 2019-03-05 09-15-34

I don't think we can go smaller than this. The font on the LC logo is not as thick as the other ones and the lettering is quite thin at smaller sizes.

**Comment by serahkiburu** [comment]
Option 3, height: 60px looks great. May I suggest an alphabetical ordering to the logos? Either:
- SWC - LC - DC or
- DC - LC - SWC

**Comment by maneesha** [comment]
@fmichonneau  Would you be able to help me understand why the CI check is still pending?  It's been almost a full day.

**Comment by fmichonneau** [comment]
it looks like a glitch in the GitHub/Travis integration. The [built](https://travis-ci.org/carpentries/carpentries.org/builds/504804092?utm_source=github_status&utm_medium=notification) has completed and passed!

**Pull request merged**
