### PR TITLE
Adds new staff (Angelique) to website

### PR DESCRIPTION
**Pull request by maneesha**

### CODE REVIEW

**Comment by maneesha** [comment]
The `Travis CI User [ci skip] update feed data` should not have been included in this PR - my mistake. I came here to fix it but also see a blog post about community in Japan added to this PR.  @serahrono  let me know if that should be separated out.

[Guide on breaking down PRs](https://github.com/swcarpentry/python-novice-inflammation/wiki/Splitting-(Breaking-down)-Pull-Requests)

**Comment by serahkiburu** [comment]
Hi @maneesha, I merged the PR for this post late last night into gh-pages, see [commit](https://github.com/carpentries/carpentries.org/commit/78ff486684ee46e073fdbb2035c9280b59e67232) and [post](https://carpentries.org/blog/2019/11/local-team-japan/). Not sure why it was added to this PR too. You can delete it from this PR

**Comment by maneesha** [comment]
@fmichonneau I'm seeing lots of other commits getting added to this PR. Do you know what's causing this?

**Comment by maneesha** [comment]
Ugh, I see... I did this PR in reverse.  :sob:
Closing this and starting over.

**Pull request closed without merging**
