### PR TITLE
Create Carpentries-Online-Workshops.md

### PR DESCRIPTION
**Pull request by elletjies**

### CODE REVIEW

**Comment by elletjies** [comment]
Still working on this document :)

**Review by serahkiburu — APPROVED** [review]
this looks great to me, thank you so much @elletjies 🙌

**Comment by serahkiburu** [comment]
please review and merge when ready @kmomar. Thanks!

**Comment by kmomar** [comment]
Looks good to me too. Merging now for publication on the 14

**Comment by elletjies** [comment]
Thank you!

**Pull request merged**
