### PR TITLE
blog: "Lessons Learned from Running Our First Online Workshop"

### PR DESCRIPTION
**Pull request by bast**
- This is based on a discussion with @serahrono.
- I am unsure about which `date` to use.
  - Today?
  - The date of the original post?
  - The publication date?
- Original post appeared here: https://coderefinery.org/blog/2020/04/14/first-online-workshop/

### CODE REVIEW

**Comment by serahkiburu** [comment]
thank you so much for this PR, @bast 🙌 we will be publishing this early next week, and I will amend the date before it goes out.

**Comment by bast** [comment]
Perfect. Thank you! Also feel free to ping me once you know the date and I can rename and adjust also.

**Comment by serahkiburu** [comment]
Good morning @bast, hoping to publish this in a bit, thank you so much for sharing these insights!

**Comment by bast** [comment]
Thanks a lot!

**Pull request merged**
