### PR TITLE
Update coc-ctte.md with current members and compositions

### PR DESCRIPTION
**Pull request by malvikasharan**
Update coc-ctte.md with current members and compositions

### CODE REVIEW

**Comment by maneesha** [comment]
Thanks @malvikasharan  I made a few small changes to formatting the headers. Does this need to be reviewed by anyone?

**Comment by malvikasharan** [comment]
Hi Maneesha. Thank you so much. Can we wait for Sarah Stamps to reply confirming changes in this PR is ok? She is the new chair of CoCc.

**Comment by maneesha** [comment]
Assigning to @dsarahstamps for review.

**Comment by maneesha** [comment]
Also tagging @acrall  as our Core Team CoC liaison.

**Comment by maneesha** [comment]
Bumping this  @dsarahstamps

**Comment by maneesha** [comment]
Following up --  @dsarahstamps @malvikasharan  @acrall 
Not sure who should approve this but I'm good with merging if one of you say it's OK

**Comment by maneesha** [comment]
Reminder - @dsarahstamps @malvikasharan @acrall

**Comment by acrall** [comment]
I met with @dsarahstamps yesterday and this matches the spreadsheet she created with committee membership.

**Pull request merged**
