### PR TITLE
Old exec council

### LINKED ISSUE #1004: New page for past Executive Council members
With time, the list of past EC members on https://carpentries.org/governance/ is growing and the information at the bottom becomes a bit drowned out. Would it be a good idea to make a separate page for past EC members?

### PR DESCRIPTION
**Pull request by maneesha**
Creates new page for former Executive Council members.  
Fixes #1004

### CODE REVIEW

**Comment by maneesha** [comment]
Tagging @lexnederbragt  for review (it's not letting me tag you as a reviewer above)

**Comment by lexnederbragt** [comment]
Hmm, things did not entirely go as intended, but #1027 is a proposal to modify this PR...

**Comment by maneesha** [comment]
@lexnederbragt  since your suggestions were pretty easy, I manually added them into this PR as I was worried about getting buried in merge conflicts if I tried to merge both.  Let me know if this looks good to you.

**Comment by lexnederbragt** [comment]
Thanks, Maneesha! This looks fine now, ready to merge. I'll close the other PR.

**Pull request merged**
