### PR TITLE
Add lightweight changelog

### PR DESCRIPTION
**Pull request by karenword**
Anticipates https://github.com/carpentries/carpentries.org/pull/848

Not sure if this is adequate? But it serves the need (for now) to support viewers in recognizing things that have changed. More detailed summary of V2 changes would take some more work.

Tagging @fmichonneau for review because I think this was his suggestion (back when we were considering more frequent incremental updates), but @serahrono may have feedback as well.

### CODE REVIEW

**Comment by fmichonneau** [comment]
Sorry to have missed this. 

I think this is great to have. It might be good to make sure there is a bullet point for each new version so it makes it easier to navigate. Also, these types of changelogs tend to be in reverse chronological order (the most recent changes at the top). The date could be written in the YYYY-MM-DD format. Another thing to consider (and I'm not 100% sure it's appropriate for the website), but links to the GitHub-archived versions could be added for each version so people could navigate to set versions in time.

**Comment by maneesha** [comment]
Thanks for your review @fmichonneau 

@karenword  are you OK with implementing the changes François has recommended?

**Comment by karenword** [comment]
Yes, thanks! I should be able to get to addressing these later this week.

**Comment by maneesha** [comment]
@karenword  is this still a draft or is it ready to merge?

**Comment by maneesha** [comment]
@karenword is this still a draft or is it ready to merge?

**Comment by maneesha** [comment]
Pinging @karenword  
Let me know if I can help.

**Comment by maneesha** [comment]
I just updated this PR to make part of the changes @fmichonneau suggested - putting things in reverse chronological order and using the YYYY-MM-DD date format.

For other things, I am looking at what's in the changelog in this file, the "last updated" information at the first line of the file, and the [actual history of this file on GitHub.](https://github.com/carpentries/carpentries.org/commits/main/pages/online-workshop-recommendations.md).    These are not entirely consistent.  We also have named versions 1.0 and 2.0 but we don't actually reference these versions anywhere (so there's nothing to indicate we're currently on v2.0, or what v1.0 looked like).  @karenword  can you share a bit more about your motivations for including the changelog so we can better consider what changes we want to list? Thanks!

**Comment by maneesha** [comment]
Checking in @karenword

**Comment by karenword** [comment]
Sorry for dropping this! Honestly, my goal was simply to have something there indicating the last change date and a summary of the changes to prevent people from having to re-read any more than strictly necessary (but also to attend to updated sections). However, I also anticipated doing more consistent updating of this document, so this may not be as useful as I expected. The fact that the "versions" are sort of blended in with smaller pull requests is a problem, but I'm not sure exactly how to approach that.

**Comment by maneesha** [comment]
@karenword  in that case I'd like to close this. We can revisit this if we decide we want more officially versioned releases.

**Pull request closed without merging**
