### PR TITLE
WIP: Blog post about CarpentryCon from Latin American attendees

### PR DESCRIPTION
**Pull request by rgaiacs**
With contribution from Paula Andrea, Francisco Palm, Gladys Nalvarte, Nicolás Palopoli, Renato Santos.

@weaverbel A review of this blog post is welcome **but please wait until Monday, 16 July to merge it**.

### CODE REVIEW

**Comment by orchid00** [comment]
@rgaiacs I might not have permissions to push
A few comments

- Please add Martinez after my name in the header, title and fig label
- Suggestion: 
we decided copycat our friends from the other side of the Atlantic and share our experience.
we decided to copycat our friends from the African continent and share our experience.
(or add to before copycat)
- Suggestion:
mentioned his surprise by the first email that I sent to him but his didn't mentioned the date, that was around middle June, 2013
mentioned his surprise to the first email that I've sent him, but he didn't mentioned the date; it was that around mid June, 2013
- Please add Heladia Salgado to the Final words and thanks, if possible order by name or last name.

thanks @rgaiacs for putting this together

**Comment by weaverbel** [comment]
Please advise when this is good to go @rgaiacs (or use the `Ready to merge` label)

**Comment by orchid00** [comment]
@weaverbel please update my last name before publishing

**Comment by rgaiacs** [comment]
> please update my last name before publishing

Done.

> Please advise when this is good to go

@weaverbel This is good to go. :-)

**Comment by GladysNalvarte** [comment]
Sorry for my late comment but there is a typo in line 92: "too many risk and uncertainties"
the correction is "too many risks and uncertainties"

**Comment by rgaiacs** [comment]
> Sorry for my late comment but there is a typo in line 92

Fixed.

**Pull request merged**
