### PR TITLE
adding bylaws RFC post

### PR DESCRIPTION
**Pull request by k8hertweck**

### CODE REVIEW

**Comment by weaverbel** [comment]
For some reason, this build failed. I have directly committed the file myself.

**Comment by weaverbel** [comment]
The post is live here: https://carpentries.org/blog/2018/08/bylaws-rfc/

**Comment by fmichonneau** [comment]
The build failure wasn't related to the content of the post, but rather to how the test infrastructure was set up for pull requests. I changed the script so pull requests shouldn't lead to error messages. I'll keep an eye on it to make sure it's the case, but feel free to ping me if you still notice failures when they shouldn't happen.

**Comment by weaverbel** [comment]
Thanks @fmichonneau - I had the exact same thing happen with other posts this week and only redoing them and then merging them myself worked. Hopefully sorted now - thanks a lot.

**Pull request closed without merging**
