### PR TITLE
add Abdulai Imoro to EC

### LINKED ISSUE #1496: Update Governance page with newly appionted EC member
The [governance](https://carpentries.org/governance/) page of our website should be updated with the newly appointed EC member's information. Here's the information:

[Abdulai Imoro](https://www.linkedin.com/in/abdulai-imoro-9a739835/)
Appointed 2022
Country: Ghana

I will send Abdulai's photo via Slack.

### PR DESCRIPTION
**Pull request by zkamvar**
I've added Abdulai Imoro to EC, but I could not get the governance page to update locally and I'm stumped as to why. 

this will fix #1496

### CODE REVIEW

**Comment by kariljordan** [comment]
@danielle06 please let us know what Abdulai's GitHub handle is so that @maneesha can add it to this PR. Thank you!

**Comment by maneesha** [comment]
I haven't tried to build this locally but the netlify page builds correctly.  Image size needs to be adjusted.  I'll come back to this shortly.

**Comment by maneesha** [comment]
GH username has been updated.

**Comment by maneesha** [comment]
Image resized.

**Pull request merged**
