### PR TITLE
Updated staff team page

### PR DESCRIPTION
**Pull request by maneesha**
Adds new images to staff page
Adds new titles to staff page
Adds team leads to staff page
Adds job plans to staff page.  Note this still needs icons as @ErinBecker [requested](https://github.com/carpentries/carpentries.org/commit/74edf8afc14b3d972038effd51b25652ba2325ce) (more info also in [Asana](https://app.asana.com/0/137453351326545/1108107802880665) ).  Will try to get to the icons in the next few days.

Would be good to have someone build this locally to have a second eye on it before merging.

### CODE REVIEW

**Comment by fmichonneau** [comment]
I built this locally and it looks great! Thanks Maneesha!

A few comments:

- It would be better to delete the old images instead of moving them. They are part of the history of the repository so we can always get them back if needed, but there is no need to keep around files that are not actively used by the website. It makes things more difficult to debug, and it makes rendering slower.

- It might be helpful to distinguish stylistically (maybe by using italics) what is the job title and what are the team memberships.

- Instead of "Lead, XXX Team", I think it'll be clearer if it said: "Lead of the XXX Team"

- I think that using icons for the job plans is going to be confusing for the visitors of the website. The other icons are for brands of social media services. Adding an icon for the job plans breaks the consistency that the user would expect from this category. I'm also not sure which icon could adequately capture the meaning of "job plan".

**Comment by kariljordan** [comment]
> I built this locally and it looks great! Thanks Maneesha!
> 
> A few comments:
> 
> * It would be better to delete the old images instead of moving them. They are part of the history of the repository so we can always get them back if needed, but there is no need to keep around files that are not actively used by the website. It makes things more difficult to debug, and it makes rendering slower.
> * It might be helpful to distinguish stylistically (maybe by using italics) what is the job title and what are the team memberships.
> * Instead of "Lead, XXX Team", I think it'll be clearer if it said: "Lead of the XXX Team"
> * I think that using icons for the job plans is going to be confusing for the visitors of the website. The other icons are for brands of social media services. Adding an icon for the job plans breaks the consistency that the user would expect from this category. I'm also not sure which icon could adequately capture the meaning of "job plan".

I agree that using icons for job plans will be a bit confusing. I like how the words **job plan** show up in the screenshot and people can click on them if they're interested.

**Comment by kariljordan** [comment]
> Meet the Carpentries staff and others who work with us

Do we need this sentence? I understand that some "staff" are independent contractors and such, but are we truly not allowed to use the word staff to indicate that we are the people who get paid to work with/for The Carpentries?

**Comment by kariljordan** [comment]
@tracykteal just explained to me why we aren't able to use the term "staff", so I'm all set with that question!

**Comment by maneesha** [comment]
I just pushed some changes based on suggestions from @fmichonneau .

@ErinBecker  had said she visioned the job plans being icons.  I wasn't sure what she meant so I asked her.  Once she responds I can update this or just go with what we have.

You can build locally again to test it out or check out this screenshot.

image

**Comment by kariljordan** [comment]
This is **super meta**, but can we say "Workshops Team Lead", etc. instead of "Lead of the Workshops Team? I'll submit a PR...

**Comment by ErinBecker** [comment]
I agree with @kariljordan about "Workshops Team Lead" rather than "Lead of the Workshops Team". The change I was going to make (listing myself as team lead for curriculum) has already been taken care of, so I'm good with the content of this now. I also like the way that the Job Plan links are showing up in the screenshot - looks much nicer and cleaner than I had envisioned. Great job @maneesha and team! I believe this is ready to merge.

**Pull request merged**
