### PR TITLE
Add Library Carpentry

### PR DESCRIPTION
**Pull request by bkmgit**

### CODE REVIEW

**Comment by maneesha** [comment]
@Talishask  can you verify this? Are all the logos trademarks of CI?  (all three lesson programs plus The Carpentries?)

**Comment by Talishask** [comment]
Thanks for pinging me @maneesha 

We cannot merge this just yet, as we have not trademarked the Library Carpentry logo. Earlier this year we transferred trademarks for SWC & DC from their founders to our fiscal sponsor. We intended to trademark LC and The Carpentries however, due to budget constraints, we decided to move forward with trademarking The Carpentries. We plan to revisit trademarking LC in strategy and budget planning next year.

**Comment by maneesha** [comment]
Assigning to @Talishask  to let us know when trademarks are confirmed.

**Comment by Talishask** [comment]
Closing this issue for now. I will reopen when we have completed trademarking.

**Pull request closed without merging**
