### PR TITLE
Add newsletter page

### PR DESCRIPTION
**Pull request by fmichonneau**
I introduce a few changes here:

- I created a Newsletter page, with a signup form and a list of past issue
- I renamed the top item from "Blog" to "Connect" with 2 subitems: "Blog" and "Newsletter"

Preview:

screenshot from 2018-04-23 10-59-31

### CODE REVIEW

**Comment by fmichonneau** [comment]
related to #95

**Comment by ErinBecker** [comment]
This looks great to me!

**Comment by tracykteal** [comment]
Looks good to me too! Will merge.

**Comment by tracykteal** [comment]
Should we also make a 'Connect' page that has an overview on connecting, including a link to Slack and the 'Join Us' page for more specific information?

**Comment by weaverbel** [comment]
Bella Bella @fmichonneau - thanks

**Comment by weaverbel** [comment]
I will keep it up to date from now on.

**Pull request merged**
