### PR TITLE
Publish Carpentries Values 

### PR DESCRIPTION
**Pull request by serahkiburu**

### CODE REVIEW

**Comment by serahkiburu** [comment]
This is how the standalone values page will look like The Nine Core Values of The Carpentries

**Review by kariljordan — APPROVED** [review]
I'm extremely proud of this work. Excellent post. Thank you @serahrono!

**Comment by tracykteal** [comment]
Thanks you @serahrono! I really like the values page as well. Very appreciative and excited for this work.

**Review by tracykteal — APPROVED** [review]
Thank you @serahrono!

**Pull request merged**
