### PR TITLE
Add blog post call for Sponsorship Task Force

### PR DESCRIPTION
**Pull request by rgaiacs**
@tracykteal This is based on our discussion.

@serahrono Can this be publish on the 22nd? Thanks.

@k8hertweck This is the item that I asked you to include in news letter.

### CODE REVIEW

**Comment by serahkiburu** [comment]
Hi @rgaiacs 

thanks for writing this post and creating a PR to get it published. 

In the second paragraph, would 
> The Executive Council determined that one way to increase our capacity by bringing more income is via a Sponsorship Programme.
convey the same message?

**Comment by rgaiacs** [comment]
Change done.

**Comment by serahkiburu** [comment]
@rgaiacs I made a couple of edits. Please have a look and let me know if you think it's good to go

**Comment by rgaiacs** [comment]
@serahrono Looks good to me.

**Pull request merged**
