### PR TITLE
make community calendar adjust for user time zone

### PR DESCRIPTION
**Pull request by maneesha**

### CODE REVIEW

**Comment by maneesha** [comment]
I think this should work but if someone else can try building this locally before merging that would be appreciated!  @jduckles  @ErinBecker

**Comment by maneesha** [comment]
I don't know what the failed check means.  @jduckles  can you help?

**Comment by jduckles** [comment]
You can ignore that particular travis message.

**Comment by maneesha** [comment]
OK @jduckles  - just to be sure then - it is OK to merge this?

**Comment by jduckles** [comment]
Yep, the failing check isn't related to your code.

**Pull request merged**
