### PR TITLE
Regional Coordinator template

### PR DESCRIPTION
**Pull request by maneesha**
This creates a template page for all RC pages to be built off of.

### CODE REVIEW

**Comment by maneesha** [comment]
This introduces a lot of back end changes that make each of the RC pages easier to build and maintain.

@sheraaronhurt - Don't worry about the code but if you can look at the preview pages -- [start here](https://deploy-preview-930--stupefied-einstein-5bde90.netlify.app/regionalcoordinators/) and take a quick look at each of the RC pages to make sure they look OK that would be great.  I've reviewed them but it would be very useful to have another eye on them.

@fmichonneau  I've created a template page and then set all the RC pages to build from that.  A code review would be very helpful! 

Once we know this all looks OK, I'll create the new DACH RC page based on this new template.

**Review by fmichonneau — APPROVED** [review]
this looks great! Thanks for doing this Maneesha!

**Comment by sheraaronhurt** [comment]
Hey @maneesha  the layout looks great. A few areas to update:

- On the RC's pages that have upcoming workshop please change the following: "Workshops with a globe icon are being held **on line**. The corresponding flag notes the country where the host organization is based" (Please change "on line" to "online")

- On the Global page please update the following paragraph to include the DACH and Nordic Regions: SherAaron works with our Regional Coordinators in Australia, Canada, New Zealand, and the United Kingdom.

**Comment by maneesha** [comment]
I have changed "online" from "on line." 
I will add the language about DACH workshops in a separate PR.

**Pull request merged**
