### PR TITLE
Revised timeline for strategic plan update

### PR DESCRIPTION
**Pull request by kariljordan**
Submitting a PR to revise the strategic plan update timeline based on feedback from the Core Team and Executive Council. For EC reference, it is issue [#145](https://github.com/carpentries-ec/conversations_ec_ed/issues/145) in the private repo for the Executive Council.

This PR needs to be approved by the Chair of the Executive Council (@sstevens2).

### CODE REVIEW

**Comment by maneesha** [comment]
Does this mean that the EC will still **assess** the plan now (or in the next few months)? Three years from Jan 2020 would be Jan 2023 and we are coming up on that.

**Comment by kariljordan** [comment]
@maneesha I provide quarterly updates to the Executive Council about our strategic plan activities, and they also follow the [strategic plan repo](https://github.com/carpentries/strategic-plan/issues) closely.

So that it is not confusing, we can change the word "assess". Since there are no concrete metrics in our strategic plan, our assessment of the deliverables will be providing a list of examples/activities under each deliverable. That's what we have been tracking in the repo.

In 2023 the EC will begin developing a **process** for writing the next iteration of our strategic plan, including what metrics we will track, how/how often, and an implementation plan. This effort will be collaborative (EC/Core Team/community as needed).

**Comment by maneesha** [comment]
This will be merged after @sstevens2  approves.

**Comment by maneesha** [comment]
Bump @sstevens2

**Comment by sstevens2** [comment]
This change is approved.  Thanks @maneesha for the bump!

**Pull request merged**
