### PR TITLE
[Blog post] summary of Community Champions call today

### PR DESCRIPTION
**Pull request by jduckles**
Blog post for Carpentry Champions call today.

### CODE REVIEW

**Comment by kariljordan** [comment]
Awesome call Jonah! Lots of buzz on Twitter as well. We try not to post on our blog on Fridays because we don’t think Friday posts get the attention they deserve. Would you be fine with us posting this early next week?

**Comment by jduckles** [comment]
No problem at all.

**Comment by kariljordan** [comment]
@kariljordan will merge on 23-Sept (Monday)

**Comment by serahkiburu** [comment]
thank you for the fantastic post @jduckles, and for reviewing and scheduling it for today, @kariljordan!

**Pull request merged**
