### PR TITLE
Create 2018-12-07-more-than-workshops.md

### PR DESCRIPTION
**Pull request by marwahaha**
cc @sabahzero @anelda @karenword @ha0ye @tracykteal

### CODE REVIEW

**Comment by ha0ye** [comment]
Looking for comments or PRs with direct edits/suggestions?

**Comment by marwahaha** [comment]
Sure, if you've got any! I'm also comfortable with the manuscript as is. Earlier edits were made via a Hackmd. I tagged all of you because you are listed as blog post authors.

**Comment by ha0ye** [comment]
The biggest thing that jumped out at me was the wording of the teaser "How can you really become part of the Carpentries community?", which *could* imply that a certain level of dedication is required to be considered a "real" member of the community. I would prefer a wording that is a bit more inviting, such as "What other ways are there to participate in the Carpentries community?".

**Comment by tracykteal** [comment]
Thank you so much for this great blog post! It's a great overview and roadmap of ways to get and be involved in the community. This got merged Friday, but we like to re-advertise at the beginning of the week too. I'll put it up on Twitter. @marwahaha or @sabahzero would you be interested in sending an email to discuss to let people know about the post?

**Comment by sabahzero** [comment]
@tracykteal sure! what's the best way to email everyone? Also happy for @marwahaha to take lead, whatever is preferred is fine by me.

**Comment by tracykteal** [comment]
Great, thanks! You can send an email to discuss@lists.carpentries.org. If you're not already subscribed to that list, you can do it here https://carpentries.topicbox.com/groups/discuss

**Comment by marwahaha** [comment]
Sabah -- go for it! :)

**Pull request merged**
