### PR TITLE
create elections blog post

### PR DESCRIPTION
**Pull request by maneesha**

### CODE REVIEW

**Comment by maneesha** [comment]
Blog post was created from a Google doc shared with me by @konrad. 

There is also a Google doc with a translation by @masamiy - I don't know how we want to include that here.

**Comment by maneesha** [comment]
One question for @konrad  -- Question 2 asks what expertise the EC needs. Could we consider rewording the first line of the answer so as not to imply that the EC already possesses these characteristics?

**Comment by maneesha** [comment]
Also last year we noted who the exiting EC members were. Could we do that again? I think it is useful to know who the new candidates will be replacing.

See last year's blog post: https://carpentries.org/blog/2021/09/executive-council-elections/

**Comment by maneesha** [comment]
Assigning to @konrad  for review and to @kmomar to merge.

**Comment by kariljordan** [comment]
> Blog post was created from a Google doc shared with me by @konrad.
> 
> There is also a Google doc with a translation by @masamiy - I don't know how we want to include that here.

The EC would like to publish all 4 blog posts (English, Japanese, Spanish, Germany] at once individually. At the top of each there should be a link to the others. For example it could read: **To view this post in Spanish click...To view this post in German click...**

**Comment by maneesha** [comment]
Thanks @kariljordan 
In that case, I would like to ask that the people doing the translations put in PRs for those posts.  I was able to review the text and formatting of the English language post but can not do so for the other posts.  Will this mean postponing the publication date of this post?

**Comment by maneesha** [comment]
Also note the text directing people to other languages should be in that language.

**Comment by yabellini** [comment]
To understand: this Is the final text for the English version?
Do we should create a new PR with the translations? 
Can you create the placeholder in this or a new PR for the other languages and then we fill with the text? 
Thanks

**Comment by masamiy** [comment]
I translated the blog post, but not forms. Should they be translated?

**Comment by konrad** [comment]
> Blog post was created from a Google doc shared with me by @konrad.
> 
> There is also a Google doc with a translation by @masamiy - I don't know how we want to include that here.

I would like to ask @masamiy to generate the markdown file as PR here based on the file @maneesha has provided.

**Comment by konrad** [comment]
> One question for @konrad -- Question 2 asks what expertise the EC needs. Could we consider rewording the first line of the answer so as not to imply that the EC already possesses these characteristics?

Thanks for raising this, @maneesha. I personally don't see a need for change as the text says "possess some of the following characteristics". I assume this makes it clear that nor all attributes must be met.

**Comment by konrad** [comment]
> Also last year we noted who the exiting EC members were. Could we do that again? I think it is useful to know who the new candidates will be replacing.
> 
> See last year's blog post: https://carpentries.org/blog/2021/09/executive-council-elections/

Very good point, @maneesha. I have added that in the Google doc version. If you agree add this to the markdown version

**Comment by konrad** [comment]
> Thanks @kariljordan In that case, I would like to ask that the people doing the translations put in PRs for those posts. I was able to review the text and formatting of the English language post but can not do so for the other posts. Will this mean postponing the publication date of this post?

I would suggest to postpone it to Friday Sep. 16. Due to the different time zones its there is a larger delay in communication. In case we have everything done tomorrow (Thursday) we could publish it already then.

**Comment by konrad** [comment]
> Also note the text directing people to other languages should be in that language.

That would mean somebody has to set up new forms. Who can do that?

**Comment by konrad** [comment]
> Also note the text directing people to other languages should be in that language.

Suggestion. All translator add there test as comment here and you add it to the post, @maneesha. For German this would be: "Um diesen Post auf Deutsch zu lesen klicke hier"

**Comment by konrad** [comment]
> I translated the blog post, but not forms. Should they be translated?

I would avoid that as this would mean that we have for each form also several version and need to combine them? What do other think regarding this?

**Comment by konrad** [comment]
@maneesha - I think your file name has a typo and a "e" is missing after the "l". Should be `2022-09-14-ec-elections.md`

**Comment by konrad** [comment]
Due to the delayed publication the file name should be changed to `2022-09-16-ec-elections.md`.

**Comment by konrad** [comment]
I would now generate a fork and add the file `2022-09-16-ec-elections_de.md`. @masamiy should generate a file called `2022-09-16-ec-elections_ja.md` and @yabellini  a file called `2022-09-16-ec-elections_es.md` following  two letter language code according to [ISO_639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes). Would that be okay, @maneesha?

**Comment by konrad** [comment]
> To understand: this Is the final text for the English version? Do we should create a new PR with the translations? Can you create the placeholder in this or a new PR for the other languages and then we fill with the text? Thanks

This is no yet the final version - the name of the positions being replaced first needs to be added by @maneesha.

**Comment by maneesha** [comment]
@konrad can we make any edits here in GitHub rather than the Google Doc? Having edits in multiple places will cause confusion and conflicts.

**Comment by maneesha** [comment]
Following up here - The current text does not imply that a candidate must possess all of the characteristics below.  It would be useful to know which of these characteristics members of the EC already have and if there are any specific characteristics the EC is looking for.  That is not clear the way it is currently worded.

> One question for @konrad -- Question 2 asks what expertise the EC needs. Could we consider rewording the first line of the answer so as not to imply that the EC already possesses these characteristics?

> > Thanks for raising this, @maneesha. I personally don't see a need for change as the text says "possess some of the following characteristics". I assume this makes it clear that nor all attributes must be met.

**Comment by kmomar** [comment]
@maneesha @konrad I have added the update from the Google doc to this PR. If that is the last change to the English version, can we have the translators please go ahead and make their PRs for the other language versions and also add a translation of the text "Read this post in [language]" as a comment in this PR so that we can add links to each of the languages at the top of the page?

@masamiy @yabellini

**Comment by konrad** [comment]
> Following up here - The current text does not imply that a candidate must possess all of the characteristics below. It would be useful to know which of these characteristics members of the EC already have and if there are any specific characteristics the EC is looking for. That is not clear the way it is currently worded.
> 
> > One question for @konrad -- Question 2 asks what expertise the EC needs. Could we consider rewording the first line of the answer so as not to imply that the EC already possesses these characteristics?
> 
> > > Thanks for raising this, @maneesha. I personally don't see a need for change as the text says "possess some of the following characteristics". I assume this makes it clear that nor all attributes must be met.

>r1

> Following up here - The current text does not imply that a candidate must possess all of the characteristics below. It would be useful to know which of these characteristics members of the EC already have and if there are any specific characteristics the EC is looking for. That is not clear the way it is currently worded.
> 
> > One question for @konrad -- Question 2 asks what expertise the EC needs. Could we consider rewording the first line of the answer so as not to imply that the EC already possesses these characteristics?
> 
> > > Thanks for raising this, @maneesha. I personally don't see a need for change as the text says "possess some of the following characteristics". I assume this makes it clear that nor all attributes must be met.

As discussed in our call (@maneesha and I) to this we keep it as it is.

**Comment by konrad** [comment]
> @maneesha @konrad I have added the update from the Google doc to this PR. If that is the last change to the English version, can we have the translators please go ahead and make their PRs for the other language versions and also add a translation of the text "Read this post in [language]" as a comment in this PR so that we can add links to each of the languages at the top of the page?
> 
> @masamiy @yabellini

Thanks, @kmomar! I am now working now on the Germany version. @masamiy and @yabellini can you please generate you PRs. Thanks!

**Comment by yabellini** [comment]
Read this post in [language] = "Lee esta entrada en Español"

**Comment by yabellini** [comment]
I did a PR, hope it is ok. I don't like work with forks :-P

**Comment by masamiy** [comment]
Japanese translation is done, as well.

Thank you and Kind Regards,
Masami

**Comment by konrad** [comment]
Many thank for creating PR #1477 and #1476, @masamiy and @yabellini! @maneesha and @kmomar is that okay for you and can you continue from here?

**Comment by kmomar** [comment]
> Many thank for creating PR #1477 and #1476, @masamiy and @yabellini! @maneesha and @kmomar is that okay for you and can you continue from here?

It seems we have all we need to publish. I'll publish when I start my workday tomorrow!

**Comment by konrad** [comment]
Great, @kmomar! Thanks to everybody!

**Pull request merged**
