### PR TITLE
Propose Changes 1 - Online Workshops

### PR DESCRIPTION
**Pull request by Talishask**
This PR is to propose changes that will go live with the pricing differentiation of online and in-person workshops. Currently estimated for Q2.

Do not merge at this time.

### CODE REVIEW

**Comment by elletjies** [comment]
I prefer this option - since it is well structured and easy to follow.

**Comment by elletjies** [comment]
@sheraaronhurt, @kariljordan , @ErinBecker  should we close this PR?

**Comment by kariljordan** [comment]
@ErinBecker and I will meet on Tuesday and get back to you, and update the team.

**Comment by sheraaronhurt** [comment]
I do believe this is going to be a larger conversation. We started this in the MGT mtg and realized that we can make a lot of changes at once to role out everything.

**Comment by maneesha** [comment]
@sheraaronhurt is it worth keeping this PR open? If we are planning significant changes (as it seems we are) then I think we'd probably want to start on a clean slate.

**Comment by maneesha** [comment]
Checking in @sheraaronhurt is it worth keeping this PR open? If we are planning significant changes (as it seems we are) then I think we'd probably want to start on a clean slate.

**Comment by sheraaronhurt** [comment]
@maneesha yes you can close this

**Pull request closed without merging**
