### PR TITLE
first draft of EC blog post previewing RFCs to be released

### PR DESCRIPTION
**Pull request by k8hertweck**
Any feedback, @carpentries/executive-council-2018 ?

### CODE REVIEW

**Comment by amyehodge** [comment]
The first sentence in the second paragraph I would say should be "The Executive Council represents the community, so we are eager to solicit input from you about the direction we're taking **WITH** these important decisions."

You also have an odd number of parentheses later in this paragraph that need to be sorted out.

Other than that, I think it looks great. I prefer not to nitpick (I first wrote knitpick, heh) these to death and get them out there unless there are massive problems. 

Well done, and thanks for this, Kate.

**Comment by k8hertweck** [comment]
Thanks @amyehodge ! I made those changes and appreciate your comments, knitpicking or otherwise :)

**Comment by weaverbel** [comment]
Please advise when ready to merge @k8hertweck (or label with `Ready to merge`)

**Comment by k8hertweck** [comment]
A thumbs up from Raniere and comments accepted from Amy, so I'm ready to merge @weaverbel (looks like I can't add labels?). Thank you!

**Pull request merged**
