### PR TITLE
Added Carpentries México

### PR DESCRIPTION
**Pull request by elletjies**
Please delete this line and the text below before submitting your contribution.

---
Thanks for contributing! 

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact The Carpentries Team at team@carpentries.org.

---

### CODE REVIEW

**Comment by maneesha** [comment]
@elletjies The error is actually unrelated to your PR.  I am looking into this separately and will merge this when I fix that.

**Comment by maneesha** [comment]
@elletjies I can't assign you as a reviewer since you are the one who put in this PR.  Can you take a look at the rendered preview page and let me know if it is ok?

**Comment by elletjies** [comment]
@elletjies all is good!

**Comment by elletjies** [comment]
@maneesha all is good you can merge.

**Pull request merged**
