### PR TITLE
Update online-workshop-recommendations.md

### PR DESCRIPTION
**Pull request by annajiat**
1. Removed ".com" from mentimeter
2. Added whenisgood.net being more accessible compared to doodle
3. Added an accessibility note, that it might not be accessible to some users, and whenisgood might be an alternative

### CODE REVIEW

**Comment by serahkiburu** [comment]
@karenword see @annajiat's suggested note against Doodle

**Comment by maneesha** [comment]
@serahrono  are you seeking review from @karenword before merging?

**Comment by maneesha** [comment]
Bumping this up

> @serahrono are you seeking review from @karenword before merging?

**Comment by annajiat** [comment]
If it helps, please find the relevant discussion from accessibility channel of slack, https://swcarpentry.slack.com/archives/CBDTKM30Q/p1604135539001200

**Comment by maneesha** [comment]
Bumping up @serahrono  @karenword

**Pull request merged**
