### PR TITLE
new post for Carpentries blog

### PR DESCRIPTION
**Pull request by stemarcotti**
King's College London Carpentries Instructor Team share their experience with online teaching of Carpentries-like workshops (Unix and Git)

### CODE REVIEW

**Comment by maneesha** [comment]
@kmomar just making sure you saw this

**Comment by kmomar** [comment]
@stemarcotti Looking over this post now looks good to me! I might make some formatting changes (changing the headline size). I can publish either Feb 24 or March 1. Please let me know your preference!

**Comment by stemarcotti** [comment]
@kmomar thank you! Either date works, whenever it's easier for you. Cheers!

**Comment by kmomar** [comment]
@stemarcotti great thank you! Scheduled to publish on Tuesday, March 1

**Pull request merged**
